### ISSUE TITLE
example of YAML configuration for role ARN

### ISSUE THREAD

**Issue by craig5** [grafana/timestream-datasource#187]
**What happened**:

I have manually configured a Grafana Enterprise instance (9.0.2) to use the Timestream. (The version of the plugin is not immediately obvious. But, this was done in just the past 2 days.

**What you expected to happen**:

We are running Grafana in a kubernetes clusters and, thus, want to configure via YAML files.
The examples provided do not show how to configure the "role ARN" (using the default, AW SDK, auth method).

So, far, I have:
```
      - name: Timestream Example
        type: grafana-timestream-datasource
        jsonData:
          authType: default
          defaultRegion: us-east-1
```

**How to reproduce it (as minimally and precisely as possible)**:

**Screenshots**

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.0.2
- Plugin version: grafana-timestream-datasource @ 2.1.0
- OS Grafana is installed on: "Kubernetes" (via the grafana chart: https://grafana.github.io/helm-charts/grafana, v6.32.1)
- User OS & Browser:
- Others:
