### ISSUE TITLE
2.10.0 breaks when installed on grafana 9.5.21

### ISSUE THREAD

**Issue by smparekh** [grafana/timestream-datasource#381]
**What happened**:

When installing the latest version of the datasource on grafana 9, the editor window errors out

**What you expected to happen**:

Datasource should work or update min version here: https://grafana.com/grafana/plugins/grafana-timestream-datasource/ 

Datasource Window:
<img width="547" alt="Image" src="https://github.com/user-attachments/assets/dd6754f9-a481-4f08-a0ea-ecaddaccf860" />

Editor Window:
<img width="845" alt="Image" src="https://github.com/user-attachments/assets/96204f4f-affb-4fd7-9299-78c96660cc1c" />

**How to reproduce it (as minimally and precisely as possible)**:

Here is a docker-compose file you can use to try
```
services:
  grafana:
    image: grafana/grafana-oss:9.5.21
    ports:
      - "3000:3000"
    environment:
      - GF_SERVER_PROTOCOL=http
      - TIMESTREAM_DB_NAME=test
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-timestream-datasource,parseable-parseable-datasource
      - GF_SERVER_HTTP_PORT=3000
      - GF_SERVER_ROOT_URL=http://%(domain)s/
```

**Screenshots**

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.5.21
- Plugin version: 2.10.0
- OS Grafana is installed on: Docker
- User OS & Browser: Chrome/Firefox
- Others:
